"use client";

import {useEffect,useMemo,useState} from "react";
import {Check,Info,MousePointerClick,RotateCcw,Search,ShieldCheck,Trash2,UserRoundCheck} from "lucide-react";
import {courses,student} from "@/data/courses";
import {categoryConfig} from "@/lib/config";
import {useStudentHistory,useTranscriptProfile} from "@/lib/use-student-history";
import {useCurriculum2022} from "@/lib/use-curriculum-2022";
import {PageTitle} from "@/components/ui";

type Overrides=Record<string,boolean>;
type CurriculumYear="2025"|"2022";
const storageKey=(year:CurriculumYear)=>`imt-lecturer-course-overrides-${year}`;

export default function ProgressChecklist(){
 const history=useStudentHistory(),profile=useTranscriptProfile(),{courses:curriculum2022}=useCurriculum2022();
 const [curriculum,setCurriculum]=useState<CurriculumYear>("2025"),[overrides,setOverrides]=useState<Overrides>({}),[query,setQuery]=useState("");
 const activeCourses=curriculum==="2025"?courses:curriculum2022;
 const transcriptPassed=useMemo(()=>new Set(curriculum==="2025"?history.filter(h=>h.status==="PASSED").map(h=>h.courseId):[]),[history,curriculum]);
 useEffect(()=>{try{const saved=localStorage.getItem(storageKey(curriculum));setOverrides(saved?JSON.parse(saved) as Overrides:{})}catch{setOverrides({})}},[curriculum]);
 const isDone=(id:string)=>overrides[id]??transcriptPassed.has(id);
 const toggle=(id:string)=>setOverrides(current=>{const next={...current,[id]:!isDone(id)};localStorage.setItem(storageKey(curriculum),JSON.stringify(next));return next});
 const restore=()=>{setOverrides({});localStorage.removeItem(storageKey(curriculum))};
 const clearAll=()=>{const next=Object.fromEntries(activeCourses.map(course=>[course.id,false]));setOverrides(next);localStorage.setItem(storageKey(curriculum),JSON.stringify(next));activeCourses.forEach(course=>localStorage.removeItem(`imt-elective-course-name-${course.id}`));window.dispatchEvent(new Event("imt-clear-elective-names"))};
 const visible=activeCourses.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())||c.code.toLowerCase().includes(query.toLowerCase()));
 const doneCourses=activeCourses.filter(c=>isDone(c.id)),doneCredits=doneCourses.reduce((sum,c)=>sum+c.credits,0),percentage=activeCourses.length?Math.min(100,Math.round(doneCredits/student.requiredCredits*100)):0;
 const displayName=profile?.name??student.name,displayNim=profile?.nim??student.nim;
 return <><PageTitle title="Verifikasi Progress Mahasiswa" subtitle="Tampilan dosen untuk memeriksa dan mengoreksi penyelesaian mata kuliah." actions={<div className="flex flex-wrap gap-2"><label className="flex items-center gap-2"><span className="text-xs font-semibold text-slate-500">Kurikulum</span><select className="field min-w-44 font-semibold" value={curriculum} onChange={e=>{setCurriculum(e.target.value as CurriculumYear);setQuery("")}}><option value="2025">IMT 2025</option><option value="2022">IMT 2022</option></select></label><button onClick={restore} className="btn btn-outline"><RotateCcw size={15}/>Pulihkan status</button><button onClick={clearAll} className="btn border border-red-200 bg-red-50 text-red-700 hover:bg-red-100"><Trash2 size={15}/>Clear All</button></div>}/>
 <div className="mb-5 flex items-start gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><Info size={18} className="mt-0.5 shrink-0"/><div><div className="font-bold">Mode verifikasi dosen · Kurikulum {curriculum}</div><p className="mt-1 text-xs leading-5 text-blue-700">Klik kartu untuk mengaktifkan atau menonaktifkan status. Koreksi dosen disimpan terpisah untuk setiap kurikulum dan dapat dipulihkan kapan saja.</p></div></div>
 <section className="card mb-5 overflow-hidden"><div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#e6edf6] font-bold text-navy">{displayName.split(" ").slice(0,2).map(x=>x[0]).join("")}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate font-bold">{displayName}</h2><span className="badge bg-blue-50 text-blue-700"><UserRoundCheck size={12}/>Mahasiswa aktif</span></div><p className="mt-1 text-xs text-slate-500">{displayNim} · IMT {curriculum} · {student.track} Track</p></div></div><div className="mt-5 progress"><div style={{width:`${percentage}%`}}/></div><div className="mt-2 flex justify-between gap-4 text-xs text-slate-500"><span>{doneCredits} dari {activeCourses.length?student.requiredCredits:0} SKS selesai</span><span className="font-bold text-emerald-700">{percentage}%</span></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Summary value={doneCredits} label="Total SKS selesai" green/><Summary value={doneCourses.length} label="Mata kuliah selesai"/><Summary value={activeCourses.length-doneCourses.length} label="Belum selesai"/></div></div></section>
 <><div className="card mb-5 p-4"><div className="grid items-center gap-4 lg:grid-cols-[minmax(260px,360px)_1fr]"><label className="relative block"><Search className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input className="field w-full !pl-11" placeholder="Cari kode atau mata kuliah..." value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="flex flex-wrap items-center gap-x-5 gap-y-2 lg:justify-end"><span className="flex items-center gap-2 text-xs text-slate-500"><MousePointerClick size={15}/>Klik kartu untuk mengubah status</span><Legend color="bg-emerald-100 ring-emerald-400" label="Selesai"/><Legend color="bg-white ring-slate-300" label="Belum selesai"/><span className="flex items-center gap-1.5 text-[11px] text-slate-600"><ShieldCheck size={13} className="text-blue-600"/>Sumber transkrip</span></div></div></div>
 <div className="space-y-5">{Array.from({length:8},(_,index)=>index+1).map(semester=>{const semesterCourses=activeCourses.filter(c=>c.semester===semester),items=visible.filter(c=>c.semester===semester),semesterDone=semesterCourses.filter(c=>isDone(c.id)).length,totalCredits=semesterCourses.reduce((sum,c)=>sum+c.credits,0);return <section key={semester} className="card overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-line bg-slate-50/80 px-5 py-4"><div><h2 className="font-bold text-navy">Semester {semester}</h2><p className="mt-0.5 text-[11px] text-slate-500">{totalCredits} SKS · {semesterDone} dari {semesterCourses.length} mata kuliah selesai</p></div>{semesterDone===semesterCourses.length&&<span className="badge bg-emerald-100 text-emerald-700"><Check size={13}/>Semester selesai</span>}</header>{items.length?<div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{items.map(course=><CourseToggle key={course.id} course={course} done={isDone(course.id)} fromTranscript={transcriptPassed.has(course.id)} overridden={course.id in overrides} onToggle={()=>toggle(course.id)}/>)}</div>:<div className="p-10 text-center text-sm text-slate-500">Tidak ada mata kuliah yang cocok dengan pencarian.</div>}</section>})}</div></></>;
}

function Summary({value,label,green=false}:{value:number;label:string;green?:boolean}){return <div className={`min-w-36 rounded-xl px-5 py-4 text-center ${green?"bg-emerald-50":"bg-slate-50"}`}><div className={`text-2xl font-bold ${green?"text-emerald-700":"text-ink"}`}>{value}</div><div className={`text-[11px] font-semibold ${green?"text-emerald-700":"text-slate-500"}`}>{label}</div></div>}
function Legend({color,label}:{color:string;label:string}){return <span className="flex items-center gap-1.5 text-[11px] text-slate-600"><i className={`h-3 w-3 rounded ring-1 ${color}`}/>{label}</span>}
function CourseToggle({course,done,fromTranscript,overridden,onToggle}:{course:(typeof courses)[number];done:boolean;fromTranscript:boolean;overridden:boolean;onToggle:()=>void}){
 const category=categoryConfig[course.category];
 return <div role="button" tabIndex={0} onClick={onToggle} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onToggle()}}} aria-pressed={done} className={`group flex min-h-[164px] min-w-0 cursor-pointer flex-col rounded-xl border p-4 text-left transition focus:outline-none focus:ring-2 focus:ring-navy/30 ${done?"border-emerald-400 bg-emerald-50 hover:bg-emerald-100/70":"border-slate-200 bg-white hover:border-slate-300 hover:shadow-md"}`} style={{borderTop:`4px solid ${done?"#169b70":category.color}`}}>
  <div className="flex items-center justify-between gap-3"><span className={`truncate text-[11px] font-extrabold tracking-wide ${done?"text-emerald-700":"text-slate-500"}`}>{course.code}</span><span className="shrink-0 text-[11px] font-bold text-slate-500">{course.credits} SKS</span></div>
  <h3 className="mt-3 break-words text-sm font-bold leading-5 text-ink">{course.name}</h3>
  {(course.category==="ELECTIVE"||course.name.toLowerCase().includes("mk pilihan"))&&<ElectiveNameInput courseId={course.id}/>}<div className="mt-auto flex min-w-0 items-end justify-between gap-3 pt-4"><div className="min-w-0"><div className="truncate text-[9px] font-bold uppercase tracking-wide" style={{color:done?"#168765":category.color}}>{category.label}</div><div className="mt-1.5 flex flex-wrap gap-1">{fromTranscript&&<Tag blue>TRANSKRIP</Tag>}{overridden&&<Tag>KOREKSI DOSEN</Tag>}</div></div><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full transition ${done?"bg-emerald-600 text-white":"border-2 border-slate-300 bg-white text-transparent group-hover:border-slate-400"}`}><Check size={17} strokeWidth={3}/></span></div>
 </div>
}
function ElectiveNameInput({courseId}:{courseId:string}){const key=`imt-elective-course-name-${courseId}`,[name,setName]=useState("");useEffect(()=>{const clear=()=>setName("");setName(localStorage.getItem(key)??"");window.addEventListener("imt-clear-elective-names",clear);return()=>window.removeEventListener("imt-clear-elective-names",clear)},[key]);return <label className="mt-3 block cursor-text" onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><span className="mb-1 block text-[9px] font-bold uppercase tracking-wide text-violet-700">MK yang diambil</span><input className="field !h-9 w-full text-xs" value={name} placeholder="Tulis nama mata kuliah..." onChange={e=>{setName(e.target.value);localStorage.setItem(key,e.target.value)}}/></label>}
function Tag({children,blue=false}:{children:React.ReactNode;blue?:boolean}){return <span className={`rounded px-1.5 py-0.5 text-[8px] font-extrabold ${blue?"bg-blue-100 text-blue-700":"bg-amber-100 text-amber-700"}`}>{children}</span>}
