"use client";

import {useEffect,useMemo,useState} from "react";
import {Check,CheckCircle2,Info,MousePointerClick,RotateCcw,Search,ShieldCheck,UserRoundCheck} from "lucide-react";
import {courses,student} from "@/data/courses";
import {categoryConfig} from "@/lib/config";
import {useStudentHistory,useTranscriptProfile} from "@/lib/use-student-history";
import {PageTitle} from "@/components/ui";

type Overrides=Record<string,boolean>;
const STORAGE_KEY="imt-lecturer-course-overrides";

export default function ProgressChecklist(){
 const history=useStudentHistory(),profile=useTranscriptProfile();
 const [overrides,setOverrides]=useState<Overrides>({}),[query,setQuery]=useState("");
 const transcriptPassed=useMemo(()=>new Set(history.filter(h=>h.status==="PASSED").map(h=>h.courseId)),[history]);
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setOverrides(JSON.parse(saved) as Overrides)}catch{}},[]);
 const isDone=(id:string)=>overrides[id]??transcriptPassed.has(id);
 const toggle=(id:string)=>setOverrides(current=>{const next={...current,[id]:!isDone(id)};localStorage.setItem(STORAGE_KEY,JSON.stringify(next));return next});
 const restore=()=>{setOverrides({});localStorage.removeItem(STORAGE_KEY)};
 const visible=courses.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())||c.code.toLowerCase().includes(query.toLowerCase()));
 const doneCourses=courses.filter(c=>isDone(c.id)),doneCredits=doneCourses.reduce((sum,c)=>sum+c.credits,0),percentage=Math.min(100,Math.round(doneCredits/student.requiredCredits*100));
 const displayName=profile?.name??student.name,displayNim=profile?.nim??student.nim;
 return <><PageTitle title="Verifikasi Progress Mahasiswa" subtitle="Tampilan dosen untuk memeriksa dan mengoreksi status penyelesaian mata kuliah." actions={<button onClick={restore} className="btn btn-outline"><RotateCcw size={15}/>Pulihkan dari transkrip</button>}/>
 <div className="mb-5 flex items-start gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><Info size={18} className="mt-0.5 shrink-0"/><div><div className="font-bold">Mode verifikasi dosen</div><p className="mt-1 text-xs leading-5 text-blue-700">Status awal mengikuti transkrip. Dosen dapat mengaktifkan atau menonaktifkan setiap mata kuliah dengan klik. Koreksi dosen disimpan terpisah dan dapat dipulihkan kapan saja.</p></div></div>
 <section className="card mb-5 overflow-hidden"><div className="grid gap-5 p-5 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-full bg-[#e6edf6] font-bold text-navy">{displayName.split(" ").slice(0,2).map(x=>x[0]).join("")}</div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{displayName}</h2><span className="badge bg-blue-50 text-blue-700"><UserRoundCheck size={12}/>Mahasiswa aktif</span></div><p className="mt-1 text-xs text-slate-500">{displayNim} · {student.curriculum} · {student.track} Track</p></div></div><div className="mt-5 progress"><div style={{width:`${percentage}%`}}/></div><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{doneCredits} dari {student.requiredCredits} SKS selesai</span><span className="font-bold text-emerald-700">{percentage}%</span></div></div><div className="grid grid-cols-2 gap-3"><div className="min-w-36 rounded-xl bg-emerald-50 px-5 py-4 text-center"><div className="text-2xl font-bold text-emerald-700">{doneCourses.length}</div><div className="text-[11px] font-semibold text-emerald-700">Mata kuliah selesai</div></div><div className="min-w-36 rounded-xl bg-slate-50 px-5 py-4 text-center"><div className="text-2xl font-bold">{courses.length-doneCourses.length}</div><div className="text-[11px] font-semibold text-slate-500">Belum selesai</div></div></div></div></section>
 <div className="mb-5 flex flex-wrap items-center gap-3"><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={16}/><input className="field w-72 pl-9" placeholder="Cari kode atau mata kuliah..." value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="flex items-center gap-2 text-xs text-slate-500"><MousePointerClick size={15}/>Klik kartu untuk mengubah status</span><div className="ml-auto flex flex-wrap gap-4 text-[11px] text-slate-600"><span className="flex items-center gap-1.5"><i className="h-3 w-3 rounded bg-emerald-100 ring-1 ring-emerald-400"/>Selesai</span><span className="flex items-center gap-1.5"><i className="h-3 w-3 rounded bg-white ring-1 ring-slate-300"/>Belum selesai</span><span className="flex items-center gap-1.5"><ShieldCheck size={13} className="text-blue-600"/>Sumber transkrip</span></div></div>
 <div className="space-y-5">{Array.from({length:8},(_,index)=>index+1).map(semester=>{const allSemesterCourses=courses.filter(c=>c.semester===semester),items=visible.filter(c=>c.semester===semester),semesterDone=allSemesterCourses.filter(c=>isDone(c.id)).length,totalCredits=allSemesterCourses.reduce((sum,c)=>sum+c.credits,0);return <section key={semester} className="card overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-line bg-slate-50/80 px-5 py-4"><div><h2 className="font-bold text-navy">Semester {semester}</h2><p className="mt-0.5 text-[11px] text-slate-500">{totalCredits} SKS · {semesterDone} dari {allSemesterCourses.length} mata kuliah selesai</p></div>{semesterDone===allSemesterCourses.length&&<span className="badge bg-emerald-100 text-emerald-700"><Check size={13}/>Semester selesai</span>}</header>{items.length?<div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{items.map(course=>{const done=isDone(course.id),fromTranscript=transcriptPassed.has(course.id),overridden=course.id in overrides,category=categoryConfig[course.category];return <button key={course.id} onClick={()=>toggle(course.id)} aria-pressed={done} className={`group flex min-h-[158px] flex-col rounded-xl border p-4 text-left transition focus:outline-none focus:ring-2 focus:ring-navy/30 ${done?"border-emerald-400 bg-emerald-50 hover:bg-emerald-100/70":"border-slate-200 bg-white hover:border-slate-300 hover:shadow-md"}`} style={{borderTop:`4px solid ${done?"#169b70":category.color}`}}><div className="flex items-center justify-between gap-3"><span className={`text-[11px] font-extrabold tracking-wide ${done?"text-emerald-700":"text-slate-500"}`}>{course.code}</span><span className="shrink-0 text-[11px] font-bold text-slate-500">{course.credits} SKS</span></div><h3 className="mt-3 text-sm font-bold leading-5 text-ink">{course.name}</h3><div className="mt-auto flex items-end justify-between gap-3 pt-4"><div className="min-w-0"><div className="truncate text-[9px] font-bold uppercase tracking-wide" style={{color:done?"#168765":category.color}}>{category.label}</div><div className="mt-1.5 flex flex-wrap gap-1">{fromTranscript&&<span className="rounded bg-blue-100 px-1.5 py-0.5 text-[8px] font-extrabold text-blue-700">TRANSKRIP</span>}{overridden&&<span className="rounded bg-amber-100 px-1.5 py-0.5 text-[8px] font-extrabold text-amber-700">KOREKSI DOSEN</span>}</div></div><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full transition ${done?"bg-emerald-600 text-white":"border-2 border-slate-300 bg-white text-transparent group-hover:border-slate-400"}`}><Check size={17} strokeWidth={3}/></span></div></button>})}</div>:<div className="p-10 text-center text-sm text-slate-500">Tidak ada mata kuliah yang cocok dengan pencarian.</div>}</section>})}</div></>;
}
