"use client";

import {useMemo,useState} from "react";
import {Background,Controls,Handle,MarkerType,Position,ReactFlow,type Edge,type Node,Panel} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import {Check,Maximize2,X} from "lucide-react";
import {courses as seedCourses} from "@/data/courses";
import {categoryConfig,statusConfig} from "@/lib/config";
import type {Course,CourseStatus} from "@/lib/types";
import {CategoryBadge,PageTitle,StatusBadge} from "@/components/ui";
import {useStudentHistory} from "@/lib/use-student-history";

type CourseNodeData={course:Course};
type SemesterNodeData={semester:number;credits:number};

function CourseNode({data}:{data:CourseNodeData}){const c=data.course,category=categoryConfig[c.category],status=statusConfig[c.status],passed=c.status==="PASSED";return <div className={`group relative w-[220px] overflow-hidden rounded-xl border shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg ${passed?"border-emerald-300 bg-emerald-50":"border-slate-200 bg-white"}`} style={{borderTop:`5px solid ${passed?"#17966b":category.color}`}}><Handle type="target" position={Position.Bottom} className="!h-2 !w-2 !border-2 !border-white !bg-red-500"/><div className="p-3.5"><div className="flex items-center justify-between gap-3"><span className={`text-[11px] font-extrabold tracking-wide ${passed?"text-emerald-700":"text-slate-500"}`}>{c.code}</span><span className="text-[11px] font-bold text-slate-500">{c.credits} SKS</span></div><div className="mt-2 min-h-10 text-[13px] font-bold leading-[18px] text-ink">{c.name}</div><div className="mt-2.5 flex items-center justify-between gap-2"><span className="max-w-[128px] truncate text-[9px] font-bold uppercase tracking-wide" style={{color:passed?"#168765":category.color}}>{category.label}</span><span className="flex shrink-0 items-center gap-1 text-[10px] font-bold" style={{color:status.color}}>{passed&&<span className="grid h-4 w-4 place-items-center rounded-full bg-emerald-600 text-white"><Check size={10} strokeWidth={3}/></span>}{status.label}</span></div></div><Handle type="source" position={Position.Top} className="!h-2 !w-2 !border-2 !border-white !bg-red-500"/></div>}

function SemesterNode({data}:{data:SemesterNodeData}){const roman=["","I","II","III","IV","V","VI","VII","VIII"][data.semester];return <div className="flex h-[104px] w-[118px] items-center justify-center rounded-2xl border-2 border-slate-300 bg-white/95 text-center shadow-sm"><div><div className="text-2xl font-black text-navy">{roman}</div><div className="mt-1 text-xs font-bold text-slate-500">{data.credits} SKS</div></div></div>}

const nodeTypes={course:CourseNode,semester:SemesterNode};
const semesterTotals=Object.fromEntries(Array.from({length:8},(_,i)=>{const semester=i+1;return [semester,seedCourses.filter(c=>c.semester===semester).reduce((n,c)=>n+c.credits,0)]}));

export default function Curriculum(){const history=useStudentHistory(),[track,setTrack]=useState("ALL"),[status,setStatus]=useState("ALL"),[selected,setSelected]=useState<Course|null>(null),[fullscreen,setFullscreen]=useState(false);
 const courses=useMemo(()=>seedCourses.map(c=>{const record=history.find(h=>h.courseId===c.id);return record?{...c,status:record.status as CourseStatus}:c}),[history]);
 const visible=useMemo(()=>courses.filter(c=>(track==="ALL"||c.track==="GENERAL"||c.track==="BOTH"||c.track===track)&&(status==="ALL"||c.status===status)),[courses,track,status]);
 const nodes=useMemo<Node[]>(()=>{const courseNodes=visible.map(c=>{const siblings=visible.filter(x=>x.semester===c.semester),index=siblings.findIndex(x=>x.id===c.id);return {id:c.id,type:"course",position:{x:index*250,y:(8-c.semester)*155},data:{course:c},draggable:false}});const maxColumns=Math.max(...Array.from({length:8},(_,i)=>visible.filter(c=>c.semester===i+1).length),1);const semesterNodes=Array.from({length:8},(_,i)=>({id:`semester-${i+1}`,type:"semester",position:{x:maxColumns*250+35,y:(8-(i+1))*155},data:{semester:i+1,credits:semesterTotals[i+1]},draggable:false,selectable:false}));return [...courseNodes,...semesterNodes]},[visible]);
 const visibleIds=new Set(visible.map(c=>c.id));
 const edges:Edge[]=visible.flatMap(c=>(c.prerequisites??[]).filter(p=>visibleIds.has(p.prerequisiteCourseId)).map(p=>({id:`${p.prerequisiteCourseId}-${c.id}`,source:p.prerequisiteCourseId,target:c.id,type:"smoothstep",animated:p.relationshipType==="RECOMMENDED_BEFORE",style:{stroke:p.relationshipType==="RECOMMENDED_BEFORE"?"#f59e0b":"#ef4444",strokeWidth:2},markerEnd:{type:MarkerType.ArrowClosed,color:p.relationshipType==="RECOMMENDED_BEFORE"?"#f59e0b":"#ef4444",width:16,height:16}})));
 const map=<div className={`${fullscreen?"fixed inset-0 z-[70] rounded-none":"card h-[720px]"} overflow-hidden bg-[#f8fafc]`}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeClick={(_,node)=>node.type==="course"&&setSelected((node.data as CourseNodeData).course)} fitView fitViewOptions={{padding:.08,maxZoom:.9}} minZoom={.25} maxZoom={1.5} nodesDraggable={false} proOptions={{hideAttribution:true}}><Background color="#d9e2ee" gap={24} size={1}/><Controls position="bottom-left"/><Panel position="top-left"><div className="rounded-xl border border-line bg-white/95 px-4 py-2 shadow-sm backdrop-blur"><div className="text-xs font-extrabold text-navy">IMT 2025 Curriculum</div><div className="text-[10px] text-slate-500">Semester I → VIII · klik kartu untuk detail</div></div></Panel><Panel position="top-right"><button className="grid h-10 w-10 place-items-center rounded-xl border border-line bg-white shadow-sm" onClick={()=>setFullscreen(x=>!x)}>{fullscreen?<X size={18}/>:<Maximize2 size={18}/>}</button></Panel></ReactFlow></div>;
 return <><PageTitle title="Curriculum Map" subtitle="Peta studi lengkap berdasarkan semester, jalur peminatan, dan status akademik Anda."/><div className="mb-4 flex flex-wrap gap-3"><select className="field" value={track} onChange={e=>setTrack(e.target.value)}><option value="ALL">Semua peminatan</option><option value="AI">AI Track</option><option value="FSD">FSD Track</option></select><select className="field" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Semua status</option>{Object.entries(statusConfig).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select><div className="ml-auto flex flex-wrap items-center gap-3">{["CORE","AI_TRACK","UNIVERSITY","ENTREPRENEURSHIP","INTERDISCIPLINARY","ENRICHMENT"].map(key=>{const item=categoryConfig[key as keyof typeof categoryConfig];return <span key={key} className="flex items-center gap-1.5 text-[10px] text-slate-500"><i className="h-2.5 w-2.5 rounded-sm" style={{background:item.color}}/>{item.label}</span>})}<span className="flex items-center gap-1.5 text-[10px] font-semibold text-emerald-700"><i className="h-2.5 w-2.5 rounded-sm bg-emerald-100 ring-1 ring-emerald-400"/>Lulus</span></div></div>{map}{selected&&<div className="fixed inset-0 z-[80] bg-black/25" onClick={()=>setSelected(null)}><aside onClick={e=>e.stopPropagation()} className="absolute right-0 top-0 h-full w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl"><button className="float-right rounded-lg p-2 hover:bg-slate-100" onClick={()=>setSelected(null)}><X/></button><div className="text-xs font-bold text-slate-500">{selected.code}</div><h2 className="mt-2 pr-10 text-xl font-bold">{selected.name}</h2><div className="mt-4 flex flex-wrap gap-2"><CategoryBadge category={selected.category}/><StatusBadge status={selected.status}/></div><dl className="mt-7 space-y-4 text-sm">{[["Jumlah SKS",`${selected.credits} SKS`],["Semester rekomendasi",`Semester ${selected.semester}`],["Jalur",selected.track],["Periode penawaran","2025/2026 Ganjil"]].map(([label,value])=><div key={label} className="border-b border-line pb-3"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl><h3 className="mt-6 text-sm font-bold">Prasyarat</h3><div className="mt-2 rounded-xl bg-slate-50 p-4 text-sm">{selected.prerequisites?.length?selected.prerequisites.map(p=><div key={p.prerequisiteCourseId}>{courses.find(c=>c.id===p.prerequisiteCourseId)?.name} · Minimal {p.minimumGrade}</div>):"Tidak memiliki prasyarat."}</div><h3 className="mt-6 text-sm font-bold">Alasan status</h3><p className="mt-2 text-sm leading-6 text-slate-600">{selected.status==="PASSED"?"Mata kuliah telah diselesaikan dan kredit sudah diperhitungkan dari riwayat akademik.":selected.status==="RECOMMENDED"?"Sesuai semester aktif dan dapat direncanakan pada KRS.":"Belum masuk rekomendasi semester aktif."}</p></aside></div>}</>}
