"use client";
import Link from "next/link";import {usePathname} from "next/navigation";import {BookMarked,BookOpen,ClipboardCheck,FilePenLine,FileUp,GraduationCap,LayoutDashboard,Map,PanelLeftClose,Settings,ShieldCheck,Tags,Waypoints,X} from "lucide-react";import {useState} from "react";import {student} from "@/data/courses";import {useTranscriptProfile} from "@/lib/use-student-history";

const studentMenu=[{href:"/",label:"Dashboard",icon:LayoutDashboard},{href:"/curriculum",label:"Curriculum Map",icon:Map},{href:"/progress-checklist",label:"Cek Progress",icon:ClipboardCheck},{href:"/planner",label:"KRS Planner",icon:BookOpen},{href:"/catalog",label:"Katalog Pilihan",icon:BookMarked},{href:"/history",label:"Riwayat Akademik",icon:GraduationCap},{href:"/transcript",label:"Impor Transkrip",icon:FileUp}];
const adminMenu=[{href:"/admin/courses",label:"Mata Kuliah",icon:Settings},{href:"/admin/curriculum-editor",label:"Editor Kurikulum",icon:FilePenLine},{href:"/admin/course-groups",label:"Kelompok Pengakuan",icon:Tags},{href:"/admin/prerequisites",label:"Prasyarat",icon:Waypoints},{href:"/admin/curriculum",label:"Layout Kurikulum",icon:ShieldCheck}];

function Profile(){const profile=useTranscriptProfile(),name=profile?.name??student.name,initials=name.split(" ").slice(0,2).map(x=>x[0]).join("").toUpperCase();return <div className="ml-auto flex items-center gap-3"><div className="text-right"><div className="text-sm font-semibold">{name}</div><div className="text-[11px] text-slate-500">Mahasiswa · AI Track</div></div><div className="grid h-9 w-9 place-items-center rounded-full bg-[#e6edf6] text-xs font-bold text-navy">{initials}</div></div>}

export function AppShell({children}:{children:React.ReactNode}){const [open,setOpen]=useState(false),path=usePathname();const renderMenu=(items:typeof studentMenu)=>items.map(({href,label,icon:Icon})=><Link onClick={()=>setOpen(false)} key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${path===href?"bg-white/12 text-white":"text-slate-300 hover:bg-white/5 hover:text-white"}`}><Icon size={18}/>{label}</Link>);return <div className="min-h-screen md:flex"><aside className={`fixed inset-y-0 left-0 z-50 w-64 bg-[#112b4c] p-5 transition-transform md:translate-x-0 ${open?"translate-x-0":"-translate-x-full"}`}><button className="absolute right-4 top-4 text-white md:hidden" onClick={()=>setOpen(false)}><X/></button><div className="mb-8 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#d9b66f] font-black text-[#17365d]">IMT</div><div><div className="font-bold text-white">KRS Planner</div><div className="text-[11px] text-slate-400">Academic Planning</div></div></div><div className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Mahasiswa</div><nav className="space-y-1">{renderMenu(studentMenu)}</nav><div className="mb-2 mt-7 px-3 text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Administrasi</div><nav className="space-y-1">{renderMenu(adminMenu)}</nav></aside>{open&&<div className="fixed inset-0 z-40 bg-black/30 md:hidden" onClick={()=>setOpen(false)}/>}<div className="min-w-0 flex-1 md:ml-64"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-line bg-white/90 px-4 backdrop-blur md:px-8"><button onClick={()=>setOpen(true)} className="md:hidden"><PanelLeftClose/></button><div className="hidden text-sm md:block"><span className="text-slate-500">Periode akademik</span><span className="ml-3 font-semibold">2025/2026 Ganjil</span></div><Profile/></header><main className="p-4 md:p-8">{children}</main></div></div>}
